# Generated by Django 5.2.5 on 2025-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('mafia', 'Мафія'), ('killer', 'Кіллер'), ('doctor', 'Лікар'), ('whore', 'Шлюха'), ('sherif', 'Шериф'), ('civilian', 'Мирний житель')], max_length=20)),
                ('is_dead', models.BooleanField()),
            ],
        ),
    ]
