# Generated by Django 5.2.5 on 2025-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0002_role_alter_gamers_is_dead_alter_gamers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamers',
            name='is_linchead',
            field=models.BooleanField(default=False),
        ),
    ]
